### ISSUE TITLE
madevent eemumu generation fails (vector code for lepton pdf not implemented)

### ISSUE THREAD

**Issue by valassi** [oliviermattelaer/mg5amc_test#10]
Hi @oliviermattelaer sorry I spoke too early about #6, the eemumu generation still fails
```
Command "import /data/avalassi/GPU2020/MG5aMC/3.1.1_lo_vectorization/CODEGEN_madonly_ee_mumu.mg" interrupted in sub-command:
"output madevent CODEGEN_madonly_ee_mumu --hel_recycling=False --vector_size=16" with error:
Exception : vector code for lepton pdf not implemented
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.
```

I will look into this. But I would keep this separate from #6 (even if it is a followup to that).

**Comment by valassi** [comment]
Olivier mentioned
"Ok the generation of the code is working now.
Now the running of the normal madevent has issue if you do not set --vector_size due depending of the value in the run_card (the mc_grouped_subproc which should normally be supported without any --vector_size)
See https://github.com/oliviermattelaer/mg5amc_test/issues/7"
I will check that, but it does not seem related.

Maybe some misocnifiguration on my side...?

**Comment by valassi** [comment]
I confirm I get this out of the box on a fresh reinstall of revision 999 - @oliviermattelaer can you reproduce that?
```
MG5_aMC>generate e+ e- > mu+ mu-
INFO: Checking for minimal orders which gives processes. 
INFO: Please specify coupling orders to bypass this step. 
INFO: Trying process: e+ e- > mu+ mu- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
1 processes with 2 diagrams generated in 0.006 s
Total: 1 processes with 2 diagrams
MG5_aMC>output madevent CODEGEN_madonly_ee_mumu --hel_recycling=False --vector_size=16
INFO: initialize a new directory: CODEGEN_madonly_ee_mumu 
INFO: remove old information in CODEGEN_madonly_ee_mumu 
INFO: Organizing processes into subprocess groups 
INFO: Generating Helas calls for process: e+ e- > mu+ mu- WEIGHTED<=4 @1 
INFO: Processing color information for process: e+ e- > mu+ mu- @1 
INFO: Creating files in directory P1_ll_ll 
Command "output madevent CODEGEN_madonly_ee_mumu --hel_recycling=False --vector_size=16" interrupted with error:
Exception : vector code for lepton pdf not implemented
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.
```
[MG5_debug.txt](https://github.com/oliviermattelaer/mg5amc_test/files/8519538/MG5_debug.txt)

**Comment by valassi** [comment]
Ok I implemented the same workaround as previously for #6 
https://github.com/madgraph5/madgraph4gpu/blob/831688b332d33618b2d23f7f2abf82c0746425d8/epochX/cudacpp/CODEGEN/MG5aMC_patches/3.1.1_lo_vectorization/madgraph/iolibs/export_v4.py#L1699
```
            if tuple(initial_states) in [([-11],[11]), ([11],[-11]), ([-13],[13]),([13],[-13])]:
                dressed_lep = True
            else:
                dressed_lep = False
            dressed_lep=False # workaround for https://github.com/oliviermattelaer/mg5amc_test/issues/10
```

Now code generation works, but clearly this needs a proper fix

**Comment by oliviermattelaer** [comment]
Here is a proper patch:
https://github.com/oliviermattelaer/mg5amc_test/commit/c040dc378e5311400c00c7930fd35f00bde8c818

**Comment by valassi** [comment]
Thanks a lot Olivier! I confirm this is ok now
