### ISSUE TITLE
hook to set the helas call writer from a plugin?

### ISSUE THREAD

**Issue by valassi** [oliviermattelaer/mg5amc_test#11]
Hi @oliviermattelaer I will post here a few issues I raised via email. I think there is a bug in the hook to set a helas call writer, I will propose a patch

This is related to https://github.com/madgraph5/madgraph4gpu/issues/341

Thanks Andrea

**Comment by valassi** [comment]
The issue is the following: as apart of the patch for bug 341, I need to set a non default Helas Call Writer. Apparently there was a hook to do that, but it does not seem to work as expected.

I tried some changes in https://github.com/madgraph5/madgraph4gpu/pull/433 and now all looks better. This inclues changes in my plugin, but also patches in upstream madgraph_interface.py.

In particular, madgraph_interface.py was
https://github.com/madgraph5/madgraph4gpu/blob/460a8f86062eae6ec0e76c2f13b055b9ece66aa2/epochX/cudacpp/CODEGEN/MG5aMC_patches/3.1.1_lo_vectorization/madgraph/interface/madgraph_interface.py#L8267
```
        # Define the helas call  writer
        if hasattr(self._curr_exporter, 'helas_exporter') and self._curr_exporter.helas_exporter:
            self._curr_helas_model = getattr(helas_call_writers, self._curr_exporter.exporter)(self._curr_model, options=options)
```
and similarly for me_exporter.

I suggest to change that to
https://github.com/madgraph5/madgraph4gpu/blob/89a0f3de332462894856a8ec5c53b37732840056/epochX/cudacpp/CODEGEN/MG5aMC_patches/3.1.1_lo_vectorization/madgraph/interface/madgraph_interface.py#L8267
```
        # Define the helas call  writer
        if hasattr(self._curr_exporter, 'helas_exporter') and self._curr_exporter.helas_exporter:
            ###self._curr_helas_model = getattr(helas_call_writers, self._curr_exporter.exporter)(self._curr_model, options=options)
            self._curr_helas_model = self._curr_exporter.helas_exporter(self._curr_model)
```

I tried this and it seems ok. This includes
https://github.com/madgraph5/madgraph4gpu/blob/fa8273448b2d255ecaacc36852445c3fa30e448c/epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/output.py#L133
```
    helas_exporter = model_handling.PLUGIN_GPUFOHelasCallWriter # this is one of the main fixes for issue #341!
```
in my PLUGIN_ProcessExporter

Does this make sense?

Thanks
Andrea

**Comment by oliviermattelaer** [comment]
Yes no issue here, that plugin hook is new and therefore not used by anyone (this is the first branch where i have put such kind of hook in place). So full freedom to edit it.

**Comment by oliviermattelaer** [comment]
Here is the patch that I put in place:
https://github.com/oliviermattelaer/mg5amc_test/commit/86c48cee793600bb04384330f84d063da0999021

Can you confirm that this was what you had in mind?

**Comment by valassi** [comment]
Hi Olivier, thanks a lot, it seems to work ok :-)

**Comment by valassi** [comment]
This fix is used in my upcoming PR https://github.com/madgraph5/madgraph4gpu/pull/433
