### ISSUE TITLE
plugin validation does not understand '3.3.1_lo_vect'

### ISSUE THREAD

**Issue by valassi** [oliviermattelaer/mg5amc_test#12]
Hi @oliviermattelaer, plugin validatiion does not understand '3.3.1_lo_vect'.
I will suggest a patch
Andrea

**Comment by valassi** [comment]
This is a proposed new version of misc.py, can you have a look if it looks ok for you?
https://raw.githubusercontent.com/madgraph5/madgraph4gpu/d45a42b0e317e998a1580f73ffc55a205c028bf2/epochX/cudacpp/CODEGEN/MG5aMC_patches/3.1.1_lo_vectorization/madgraph/various/misc.py

Essentially
- it displays the version being validated against
- it treats 3.3.1_lo_vect as 3.3.1 in the validation

Minor issue, up to you :-)
Thanks

**Comment by oliviermattelaer** [comment]
merged in rev 1003(https://github.com/oliviermattelaer/mg5amc_test/commit/fabfb83975a45d8531f26b50ec7b3fa75362e93e)

**Comment by valassi** [comment]
Thanks Olivier!
