### ISSUE TITLE
Simple ee->mumu returns 0 cross section in 311 branch

### ISSUE THREAD

**Issue by valassi** [oliviermattelaer/mg5amc_test#13]
Hi @oliviermattelaer, following up on the tests I presented today.

I wanted to check the xsec of a simple eemumu process and I saw that it is 0 in tests of my generated eemumu.mad.

To be sure, I went back to the default MG (this repo, branch 311) and I get the same. I do the following
```
generate e+ e- > mu+ mu-
output pippo --vector_size=32
launch pippo
```

I get eventually
```
INFO: Running Survey 
Creating Jobs
Working on SubProcesses
INFO: Compiling for process 1/1. 
INFO:     P1_ll_ll  
DEBUG: nb_hel: 4 zero amp: 0 bad_amps_hel: 0/8 
INFO:     P1_ll_ll  
INFO:  Idle: 1,  Running: 0,  Completed: 0 [ current time: 17h19 ] 
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  4.2s  ] 
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  4.2s  ] 
INFO: End survey 
refine 10000
Creating Jobs
INFO: Refine results to 10000 
INFO: Generating 10000.0 unweighted events. 
sum of cpu time of last step: 5 seconds
INFO: Effective Luminosity 1.2e+103 pb^-1 
INFO: need to improve 0 channels 
Survey return zero cross section. 
   Typical reasons are the following:
   1) A massive s-channel particle has a width set to zero.
   2) The pdf are zero for at least one of the initial state particles
      or you are using maxjetflavor=4 for initial state b:s.
   3) The cuts are too strong.
   Please check/correct your param_card and/or your run_card.
Zero result detected: See https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/FAQ-General-14
INFO:  
```

What should I do? Thanks Andrea

PS By the way, without vector-size 32, it is much worse, `DiscreteSampler:: Error in subroutine DS_get_point, dimension 'grouped_processes' not found.`... I guess this is issue #7?

**Comment by oliviermattelaer** [comment]
```
PS By the way, without vector-size 32, it is much worse, DiscreteSampler:: Error in subroutine DS_get_point, dimension 'grouped_processes' not found.... I guess this is issue https://github.com/oliviermattelaer/mg5amc_test/issues/7?
```
yes this is one of the issue that I want to fix with the merge with 3.4.0 (even if indeed this is not an issue of the merging itself)

**Comment by valassi** [comment]
Thanks Olivier. Any suggestion for the zero cross section?

**Comment by oliviermattelaer** [comment]
Not yet, focussing on having back number without the --vector_size.
Do you think that I should put more priority on this zero cross-section?

**Comment by valassi** [comment]
> Not yet, focussing on having back number without the --vector_size. Do you think that I should put more priority on this zero cross-section?

Hi Olivier, thanks. Hm, maybe yes. I think the 0 cross section in eemumu may hide something else. In any case I have no idea where to look for this.

I am looking at other things (essentially I now manage to run fortran + cuda on GPU! but codegen is getting messy.. at some point I will ned to give you a patch upstream for fortran). Very many issues, so I am bit losing track where your own effort is most needed, sorry. But yes I think the 0 cross section is important - and then also the random choice of color and helicity in the api. The issue without __vector size is not a blocker for me.

**Comment by oliviermattelaer** [comment]
Hi,

I guess that i will not have the time to fix it today, but the issue is quite harmless, it is just that the PDF is not correctly set instead of being set to one in this case.
So will fix it tomorow but really nothing to worry about here.

**Comment by valassi** [comment]
Uh very good, the simpler to fix the better it is ;-)
Thanks a lot
Andrea

**Comment by oliviermattelaer** [comment]
fixed: 
https://bazaar.launchpad.net/~maddevelopers/mg5amcnlo/3.1.1_lo_vectorization/revision/1006

**Comment by valassi** [comment]
Thanks Olivier, I confirm the xsec for eemumu is no longer zero once I move to rev 1009 in PR https://github.com/madgraph5/madgraph4gpu/pull/462 (https://github.com/madgraph5/madgraph4gpu/pull/462/commits/009f7e21ee26127308d06be5dc38cb7028cc6fe7)
