### ISSUE TITLE
pass amp2() to a list of size LMAXCONFIGS (number of channel) rather than MAXAMPS

### ISSUE THREAD

**Issue by oliviermattelaer** [oliviermattelaer/mg5amc_test#19]
# changing the call of channel from diagram to channel
## usefull information:

- the size of channel is given by LMAXCONFIGS
- one G directory is associated to various channel (channel choice is vectorised) 
  - the current channel is given by ICONFIG (common variable)
     - initialize in auto_dsig.f (template super_auto_dsig) within either dsigproc or dsigproc_vec
  - the list of currently possible choice of channel are in SYMCONF
    - SYMCONF is defined via "symfact.dat" in auto_dsig.f
    -  SYMCONF(0) is the number of channel related by symmetry 
    - SYMCONF(X) gives the symmetric channel number
  - The index of the current channel is stored within the variable ICONF
   - in auto_dsig.f : `ICONFIG=SYMCONF(ICONF)`
  -  CONFSUB(X,i) gives the link for matrix-element "X" (i.e. 1 most of the time) for channel "i" and returns the amplitude number associated
    -  `SUBDIAG(I) = CONFSUB(I,SYMCONF(ICONF))` (in auto_dsig.f)
- current the multi-channel is done via "Channel=subdiag(1)" ( 1 should be replace by 2 if looking at auto_dsig2.f)

- ICONF is the current symmetric channel used for this event (not this is always the same for NB_PAGE consecutive events)
   - ICONF is in the signature of ` DSIG_VEC` and of `DSIG1_VEC`
   -  the line `CHANNEL = SUBDIAG(1)`  is inside DSIG1_VEC
     - the line is a templated one  `CHANNEL = %(get_channel)s` (due to the grouping/no grouping?) 
        - replace_dict['get_channel'] = "SUBDIAG(%s)" % proc_id
        - replace_dict['get_channel'] = "MAPCONFIG(ICONFIG)" (need to check if ICONFIG is not needed here)
   
## selection of the channel (old method)

 - the choice is done in select_grouping (returned as local variable) (once for all event in a page)
 - the setup of the choice is done in `PREPARE_GROUPING_CHOICE` (called once per event)
    - this call dsigproc [still in autodsig.f] which has the iconf as argument
       - the function does update SUBDIAG(X) `SUBDIAG(I) = CONFSUB(I,SYMCONF(ICONF))`
       - this call dsigX [going to autodsigX.f] which does not have iconf as argument   
          - currently setup channel via `CHANNEL = SUBDIAG(1)` 

## color selection information

note that the color selection is based on 
```
c
c   Choose the config (diagram) which was actually used to produce the event
c
c   ...unless the diagram is passed in igraphs(1); then use that diagram
      lconfig=iconfig
      if (ickkw.gt.0) then
         if (btest(mlevel,3)) then
            write(*,*)'unwgt.f: write out diagram ',igraphs(1)
         endif
         lconfig=igraphs(1)
      endif
```
and then use `icolamp(1,lconfig,iproc)` to see if a jamp2 is LC or not.
Note that for MLM, we do have the following:
```
c     If present channel among graphs, use only this channel
c     This is important when we have mixed QED-QCD
            do i=1,igraphs(0)
               if (igraphs(i).eq.this_config) then
                  igraphs(0)=1
                  igraphs(1)=this_config
                  exit
               endif
            enddo
```

# New conclusion (for changing the call of channel from diagram to channel)
- [x]  one would like to replace `CHANNEL = SUBDIAG(1)` by  `CHANNEL = ICONFIG`
   - [x] was previously changed to  `ICONF`
   - [x] probably one can rename channel by ICONFIG (or the opposite)
 - [x] one would like to replace `CHANNEL = MAPCONFIG(ICONFIG)` by  `CHANNEL = ICONFIG` (tbc)
   - [x] no need of templating anymore?
  - [x] ICONFIG is passed as a common (no need to change signature)
    - [x] we added ICONF within the signature of DSIGX  (~150) -> remove
    - [x] need to re-update the call to dsig %(call_dsig_proc_lines)s 
    - [x] this requires to pass explicitely, ??? for ungrouped scenario (tbd) -> remove
 - [x] need to update the call of DSIGX when call for mode=1 with a dummy iconf here (need check)
  - [x] need to change the size definition of AMP2 (in template of matrix_XXX)
     - [x] check that lmaxconfigs is indeed defined for madevent not grouped
     - [x]  check that lmaxconfigs is indeed defined for madspin
     - [x]  need to check if no change needed in madspin (keeping n_max_cg so far)
 - [x] need to update the loop over amplitude for MC
     - [x] madevent grouped
     - [x] madevent non grouped (need check)
         - [x] need change to the definition of `%(set_amp2_line)s` 
 - [x] need to change the definition of the AMP2 in fortran code (see next section)
 - [ ] 
# conclusion (for changing the call of channel from diagram to channel) --outdated--
 - [x]  one would like to replace `CHANNEL = SUBDIAG(1)` by  `CHANNEL = ICONF`
 - [x] one would like to replace `CHANNEL = MAPCONFIG(ICONFIG)` by  `CHANNEL = ICONFIG` (tbc)
 - [x] this requires to pass explicitely, ICONF within the signature of DSIGX  (~150)
    - [x] need to update the call to dsig %(call_dsig_proc_lines)s 
 - [x]  this requires to pass explicitely, ICONF within the signature of DSIGX_VEC (~363)
 - [x] this requires to pass explicitely, ??? for ungrouped scenario (tbd)
 - [x] need to update the call of DSIGX when call for mode=1 with a dummy iconf here 
 - [x] need to change the size definition of AMP2 (in template of matrix_XXX)
     -  check that lmaxconfigs is indeed defined for madevent not grouped
     - [x]  check that lmaxconfigs is indeed defined for madspin
     -   need to check if no change needed in madspin (keeping n_max_cg so far)
 -  need to update the loop over amplitude for MC
     - [x] madevent grouped
     -  madevent non grouped (need check)
         -  need change to the definition of `%(set_amp2_line)s` 
 -  need to change the definition of the AMP2 in fortran code (see next section)

# update of the amp2
 - carefull here may case are using amp2
 - FKS 
 - loop induced
 - madevent 
 - madevent no grouping
 - ....
 
All template where amp2_lines is (needed) to be defined
```
./iolibs/template_files/matrix_madevent_v4.inc:279:%(amp2_lines)s
./iolibs/template_files/matrix_standalone_matchbox.inc:120:%(amp2_lines)s
./iolibs/template_files/matrix_method_python.inc:85:        %(amp2_lines)s
./iolibs/template_files/matrix_madevent_group_v4_hel.inc:264:        ${amp2_lines}
./iolibs/template_files/matrix_standalone_msP_v4.inc:122:%(amp2_lines)s
./iolibs/template_files/matrix_madevent_group_v4.inc:374:%(amp2_lines)s
./iolibs/template_files/matrix_standalone_v4.inc:225:%(amp2_lines)s
```
associated function to fill them:
```
[madgraph]$ grep get_amp2_lines . -rin
./iolibs/export_v4.py:1258:    def get_amp2_lines(self, matrix_element, config_map = [], replace_dict=None):
./iolibs/export_python.py:265:    def get_amp2_lines(self, matrix_element, config_map = []):
./madevent/hel_recycle.py:545:    def get_amp2_lines(self, line):
./loop/loop_exporters.py:3275:    def get_amp2_lines(self, *args, **opts):
./loop/loop_exporters.py:3353:    def get_amp2_lines(self, matrix_element, replace_dict, config_map):
./loop/loop_exporters.py:3515:    def get_amp2_lines(self, matrix_element, replace_dict, config_map):
```
 - export_fks.py does not overwrite get_amp2_lines -> likely use the one of madevent (WARNING)
 - export_python.py defines it (does not seemed to be used --can likely be removed-- )
 - loop_exporter defines it (likely for loop-induced case)
 - madspin defines it too (likely used to determine channel/process need to check definition)

## status in madevent code (grouped version)

```
        DO I=1,LMAXCONFIGS
            J = CONFSUB(%(proc_id)s, I) 
            if (J.ne.0) then
            if(sde_strat.eq.1) then
                 AMP2(J) = AMP2(J) * GET_CHANNEL_CUT(P, I)
                 XTOT=XTOT+AMP2(J)
            else
                 AMP2(J) = GET_CHANNEL_CUT(P, I)
                 XTOT=XTOT+AMP2(J)
            endif
            endif
        ENDDO
        IF (XTOT.NE.0D0) THEN
                ANS=ANS*AMP2(channel)/XTOT
```
 - get_channel_cut() already use channel index 
 - is it possible that J = 0 ??? (Yes, for some process, some channel might not be associate to any amplitude [not an issue]
 
## status in madevent (not grouped)

```
    IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NDIAGS
            XTOT=XTOT+AMP2(I)
        ENDDO
        IF (XTOT.NE.0D0) THEN
%(set_amp2_line)s
```
with set_amp2_lines setup as 
```
./iolibs/export_v4.py:4629:                        'set_amp2_line': 'ANS=ANS*AMP2(MAPCONFIG(ICONFIG))/XTOT'}
./iolibs/export_v4.py:4709:        #     replace_dict['set_amp2_line'] = "ANS=ANS*AMP2(SUBDIAG(%s))/XTOT" % \
./iolibs/export_v4.py:4714:        #     replace_dict['set_amp2_line'] = "ANS=ANS*AMP2(MAPCONFIG(ICONFIG))/XTOT"
```

## status in loop-induced
```
DOUBLE PRECISION AMP2(MAXAMPS)
 REAL*8 ML_AMP2(NLOOPDIAGRAMS)
```
weird initialization (up to NLOOPDIAGRAMPS, not MAXAMPS):
```
      IF (MULTI_CHANNEL) THEN
	DO I=1,NLOOPDIAGRAMS
          AMP2(I)=0D0
        ENDDO
	JAMP2(0)=1
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
	ENDDO
      ENDIF
```
actually defined as (same weirdness)
```
              DO JJ=1,NLOOPDIAGRAMS
                AMP2(JJ) = AMP2(JJ)+ ML_AMP2(JJ)
              ENDDO
```
multi-channel factor is handle like:
```
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NLOOPDIAGRAMS
          XTOT=XTOT+AMP2(I)
        ENDDO
        IF (MULTICHANNEL_THRES.GE.0.0D0) THEN
          IF (XTOT.LT.MULTICHANNEL_THRES*(DABS(ANS)/HEL_JACOBIAN)) THEN
            INTERFERENCE_CONTRIB = (MULTICHANNEL_THRES*(DABS(ANS)
     $       /HEL_JACOBIAN))
            AMP2(SUBDIAG(1)) = AMP2(SUBDIAG(1)) +
     $        (INTERFERENCE_CONTRIB/NMULTICHANNELS)
            XTOT = XTOT + INTERFERENCE_CONTRIB
          ENDIF
        ENDIF
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(SUBDIAG(1))/XTOT
```

## status in madspin

```
[MadSpin]$ grep amp2 . -rin
./decay.py:1146:#         use the AMP2 index to label the self.topologies
./decay.py:1873:#                                                                            (called AMP2 in mg)
./decay.py:1885:        #print "Cumulative AMP2 values: "
./src/driver.f:69:      DOUBLE PRECISION AMP2(n_max_cg)
./src/driver.f:70:      COMMON/TO_AMPS/  AMP2
./src/driver.f:173:      amp2(i)=0d0
./src/driver.f:241:                 amp2(k)=0d0
./src/driver.f:352:                 amp2(k)=0d0
./src/driver.f:502:      DOUBLE PRECISION AMP2(n_max_cg)
./src/driver.f:503:      COMMON/TO_AMPS/  AMP2
./src/driver.f:515:         cumulweight(i)=amp2(mapconfig(i))+cumulweight(i-1)
./src/driver.f:534:     -  amp2, cumulweight
./src/driver_prod.f:27:      DOUBLE PRECISION AMP2(n_max_cg)
./src/driver_prod.f:28:      COMMON/TO_AMPS/  AMP2
./src/driver_prod.f:75:      amp2(i)=0d0
./src/driver_prod.f:92:      write(*,*) amp2(i)
./src/driver_decay.f:27:      DOUBLE PRECISION AMP2(n_max_cg)
./src/driver_decay.f:28:      COMMON/TO_AMPS/  AMP2
```
seems relatively similar to the non grouped case. So we can do the update here if we change src/driver.f and src_driver_prod.f (likely driver_decay is not really needed).

## status in madfks
```
[P0_gg_ttx]$ grep amp2 *.f -in  | grep jamp2 -vi
born.f:144:      AMP2(1:NGRAPHS)=AMP2B(1:NGRAPHS)  ! amp2 just needs to be copyed
born.f:290:        AMP2(JJ)=0D0
born.f:525:            AMP2(I)=AMP2(I)+AMP(I)*DCONJG(AMP(I))
fks_singular.f:1187:            xtot=xtot+amp2(mapconfig(i,0))
fks_singular.f:1190:            enhance=amp2(mapconfig(this_config,0))/xtot
fks_singular.f:1234:               xtot=xtot+amp2(mapconfig(i,0))
fks_singular.f:1237:               enhance_real=amp2(mapconfig(this_config,0))/xtot
symmetry_fks_v3.f:151:         saveamp(mapconfig(j)) = amp2(mapconfig(j))
symmetry_fks_v3.f:188:                  diff=abs((amp2(mapconfig(j))-saveamp(mapconfig(k)))
symmetry_fks_v3.f:189:     &                 /(amp2(mapconfig(j))+1d-99))
```

- amp2 definition is done via a "stupid" loop over the amplitude -> no logic at all here 
- so they should not be any call to the lines defining the set of amp2 (so no clash)
- did not found the definition/assignment of amp2b (actually the same as amp2?) -> maybe ask Marco
   - SubProcesses/P0_uux_ttx/born.f:54:      COMMON/TO_AMPS_BORN/  AMP2B,       JAMP2B
   - SubProcesses/P0_uux_ttx/born.f:262:      COMMON/TO_AMPS_BORN/  AMP2,       JAMP2

## conclusion
 - [x] be sure to not touch loop-induced
 - [x] be sure to not touch FKS
 - [x] update export_v4
   - [x] for grouped mode
   - [x] for MG4 mode (no grouping)  
 - [x] check that madspin is still working
 - [x] forbid madweight/matchbox output

**Comment by valassi** [comment]
Hi Olivier, I assume this is what you had mentioned, namely use the channel id in [1,nchannels] rather than in [1,ndiagrams], where nchannels<=ndiagrams?

If this is the case, let me know when done, so I can also adapt cudacpp. Thanks!
Andrea

**Comment by oliviermattelaer** [comment]
> Hi Olivier, I assume this is what you had mentioned, namely use the channel id in [1,nchannels] rather than in [1,ndiagrams], where nchannels<=ndiagrams?
> 
> If this is the case, let me know when done, so I can also adapt cudacpp. Thanks! Andrea

yes that is the point. I will put that in a parralel branch and will put you as reviewer such that you will be able to sync the update

**Comment by oliviermattelaer** [comment]
status for today:
- grouped madevent implemented (and is compiling)
  - return wrong cross-section for p p > t t~ (only  306.3 pb) -> fixed
  - [x] need to change some variable ICONF -> ICONFIG (in all auto_dsigX.f at leat)
- rest has some change but no check (not even that it does compile)

**Comment by oliviermattelaer** [comment]
Note from today:
ICONFIG is actually already defined in most of those function via a common block
- so likely need to remove many of the changes above.
- one confusion is that iconf is not the same as iconfig:
  - `ICONFIG=SYMCONF(ICONF)`
     - SYMCONF is the list of "equivalent" channel of integration (on which we do monte-carlo)
     - ICONFIG is the really the "current" channel of integration
     - ICONF is the index in the list of equivalent channel of integration 
- need to check all the points above to see how this impact the way to modify the code 

starting post updated accordingly and new plan mapped accordingly

**Comment by oliviermattelaer** [comment]
# madevent grouped checked
 - [x] p p > t t~ (vect_size set) 
 - [x] p p > t t~ (no vect_size set) 
 - [x] p p > t t~ g g (vect_size set) (expected: Cross-section :   255.8 +- 0.7758 pb)
   - 256.7 +- 0.8502 pb 
 - [x] p p > t t~ g g (no vect_size set) (expected: Cross-section :   255.8 +- 0.7758 pb)
   - evaluated at      Cross-section :   256.7 +- 0.6929 pb

# madevent (group_subprocesses False)
 - [x] p p > t t~  
   -  Cross-section :  504.3 +- 0.5483 pb (expected 505)
   -  issue: running of alpha_s is not handled correctly...
     - fixed_scale run is working (691 +- 0.7622 pb for both) (here scale set at 100GeV)
 - [ ] p p > t t~ g g  (expected: Cross-section :   255.8 +- 0.7758 pb)
   - multiple crash:
    - Fortran runtime error: Index '32760' of dimension 1 of array 'imap' above upper bound of 6  
      - At line 669 of file cluster.f
      -  issue seems not related to this branch -> https://github.com/mg5amcnlo/mg5amcnlo/issues/6
    - matrix.f has now valid for the amp2
- [x] g g > t t~ g   (expected: Cross-section : 413 +- 1.311 pb)
   - [x] crash with  " Error: failed to reduce to color indices:            1           1" 
   - [x]  returned 413 +- 1.314 pb
- [x] p p > t t~ g   (expected: Cross-section :  434.1 +- 1.38 pb) (returned  434.1 +- 1.38 pb)

# MadSpin
 - [x] p p > t t~

**Comment by oliviermattelaer** [comment]
@valassi  

This branch (lo_vect_diagid) is effectively changing the madevent to define amp2 following the channel numbering rather than the diagram one. 

This is important for the color since this allows to have the same index for the knowledge of which color is allowed as the one for the multi-channel. 

I will still improve this branch to be sure/upgrade other mode to have consistent code and/or be sure that everything is fine (like loop-induced/....)

**Comment by oliviermattelaer** [comment]
note on configuration information:
- **handling of the parameter from the input file**:
   - the information from the input file is assigned to dconfig which is split to the
       -  integer part (iconfig) 
          - store within a common block (to_diag_number) only linked in addmothers.f but not used.
          -   pass as parameters to map_invariants as maxcfig=mincfig(both set to iconfig) 
          -  both maxcfig=mincfig are stored in the common block (to_configs)
       -  the ternary encoding part (jconfig) (not stored but use to setup other configuration variable related to BW)
- **handling in the phase-space integrator (dsample.f)**
   - the value of IPOLE/ICONFIG (dsample.f use IPOLE while genps.f use ICONFIG) is selected whitin sample_get_config
     - as mincfg=maxcfg it is automatically set to mincfg
     - note the selection if mincfg!=maxcfg seems to assume that mincfg=1 (code not used anymore, actually based on  nconfigs which is hardcoded to one in driver.f)  
   - Then the value of IPOLE/ICONFIG is passed has parameter to genps.f via the call to x_to_f_arg(...)
 - **handling in the momenta generation (genps.f)**
   - first things is to call configure_integral(iconfig,mincfig,maxcfig, ...)
   - then we have the line 
      ``` c        Start graph mapping
         do i=1,mapconfig(0)
            if (mapconfig(i) .eq. iconfig) this_config=i
         enddo
         iconfig = this_config
      ``` 
      redefining the value of iconfig according to mapconfig (mapconfig seems to be the identity when group_subprocesses is on True, it certainly is not when group_subprocesses is on False)
        - [ ] need to understand how mapconfig is setup (part of configs.inc). and both mode
    - In other word, now iconfig is (always) the INDEX of the configuration for file like configs.inc (iforest/...)
    - This value of iconfig/this_config is stored as common in the to_mconfigs
 - **handling in the function evaluation (auto_dsig.f) GROUPED MODE**
   - the value of iconfig is passed via the to_mconfigs common block (so this is the index for iforest/...)
   - Then one look at the PDF (+potentially importance sampling) to select ICONF which is a value between 1 and SYMCONF(0)
   - Then dsig is calling dsigproc passing as argument ICONF
   -  dsigproc is then assigning iconfig value via **ICONFIG=SYMCONF(ICONF)**
      - symconf is based to the symmetry.dat input (tracking identical channel related by permutation) 
   -  CONFSUB(X,i) gives the link for matrix-element "X" (i.e. 1 most of the time) for channel "i" and returns the amplitude number associated
    -  `SUBDIAG(I) = CONFSUB(I,SYMCONF(ICONF))` (in auto_dsig.f)
   -  which does then overwrite the value in to_mconfigs common block
  - **handling in the function evaluation (auto_dsigX.f) GROUPED MODE**
   - the call to dsigX() does not contain channel information 
   - this is passed via the to_mconfigs common block
   - but this is NOT used within that function 
  - **handling in the function evaluation (matrixX.f) GROUPED MODE** 
   - The value of the channel is not passed as argument
   - the value of iconfig is passed by common block but is not used!
   - The selected AMP2() is selected via the SUBDIAG(1) 
##Common block usage

*to_diag_number*
 - in driver.f (assignment)
 - in addmothers.f (but not used 
   - [ ] to remove (?)

*to_configs
  - in driver.f (assignment)
  - in addmothers.f (but not used 
   - [ ] to remove (?)
  - in unwgt.f (but not used)
   - [ ] to remove (?)
  - in auto_dsigX.f (but not used)
   - [ ] to remove (?)
  - in dsample.f (calling x_to_f_arg(IPOLE, MINCFG, MAXCFG)
    - IPOLE in dsample.f is assigned to ICONFIG in genps.f
    - the value of IPOLE is   

*to_mconfigs*
  - cluster.f
  - genps.f
  - auto_dsig.f
  - matrix.f
  - cluster.f
  - addmothers.f
  - reweight.f
  - myamp.f
  - setcuts.f

**Comment by valassi** [comment]
Hi Olivier, thanks for keeping me in the loop :-)

I am not sure I can help though... but I can only confirm that the AMP2 lines are those that seemed to be affected by lo_vect_diag and all the changes around that. From your posts I understand that indeed quite some cleanup may be useful here...

Thanks Andrea
