### ISSUE TITLE
JAMP2 dimensions - difference between MAXFLOW and NCOLOR?

### ISSUE THREAD

**Issue by valassi** [oliviermattelaer/mg5amc_test#21]
There are two (or more) different sizes used for JAMP2

https://github.com/valassi/madgraph4gpu/blob/8710108a56a115254a590335d6b8da002f6de66d/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/matrix1.f#L81
```
 DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
```

https://github.com/valassi/madgraph4gpu/blob/8710108a56a115254a590335d6b8da002f6de66d/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/matrix1.f#L150
```
        JAMP2(0)=2
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
        ENDDO
```

https://github.com/valassi/madgraph4gpu/blob/8710108a56a115254a590335d6b8da002f6de66d/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/matrix1.f#L446
```
      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO
            JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))
          ENDDO
        ENDDO
      ENDDO
```

Main question, what is the difference between NCOLOR and MAXFLOW?

**Comment by valassi** [comment]
> Main question, what is the difference between NCOLOR and MAXFLOW?

Answering myself, they seem to contain the same number, in different variables... so just some code that could be simplified to make it clearer

**Comment by oliviermattelaer** [comment]
This seems possible that maxflows to be bigger than ncolor.

export_v4.py:2690:        ncolor = max(1, len(matrix_element.get('color_basis')))
export_v4.py:2691:        replace_dict['ncolor'] = ncolor
export_v4.py:5711: maxflows = max(maxflows, ncolor)

This happens when fortran has more than one matrix-element in the same directory (which should lead to different cudacpp library(?)) and then maxflows is the maximum of ncolor of each matrix-element

**Comment by valassi** [comment]
Hi Olivier, thanks. If you ar ereferring to the fact that cudacpp assumes a single matrix1.f (no matrix2.f) that is certainly true. At some point we should add a process where we can test that too - can you suggest one such process?

By the way is this the same as the assumption that nprocesses=1? See also https://github.com/madgraph5/madgraph4gpu/issues/272

**Comment by oliviermattelaer** [comment]
For a case with multiple matrix-element, one should look at QED processes
maybe the simplest one is  (but i did not check it)
p p > w+ z

It should not be the same as nprocesses=1 but it might be a way to handle it actually
