### ISSUE TITLE
normal code (no --vector_size) does not support mc_grouped_subproc = True anymore

### ISSUE THREAD

**Issue by oliviermattelaer** [oliviermattelaer/mg5amc_test#7]
generate p p > mu+ m-
output
launch

is an example of the issue

**Comment by oliviermattelaer** [comment]
from https://bazaar.launchpad.net/~maddevelopers/mg5amcnlo/3.1.1_lo_vectorization/revision/1005
```
generate p p > t t~
output
launch
```
now compiles ... but returns wrong cross-section (334 instead of the normal 504.7 that one gets when setting --vector_size=X (X>1)

**Comment by valassi** [comment]
Thanks... hm I will stay with th eversion before then for the moment ;-)

**Comment by oliviermattelaer** [comment]
(quick) Update on the "p p > t t~" that fails with "--vector_size=1" (or no --vector_size)
If i do run with "set fixed_scale 100"
then I got 
```
Cross-section :   692.6 +- 0.8957 pb
```
while the LTS version returns
```
Cross-section :   692.8 +- 1.126 pb
```

So the issue is (seems to be) related to the alphas running.

(second update) after: https://bazaar.launchpad.net/~maddevelopers/mg5amcnlo/3.1.1_lo_vectorization/revision/1007

dynamical scale with HT/2 is back to normal:
```
 Cross-section :   505.5 +- 0.6627 pb (versus in the LTS: 505.8 +- 0.8033 pb)
```

However when using MLM scale  this is still off
```
LO_VECT:  249.2 +- 0.3562 pb
LTS: 505.8 +- 0.8033 pb
```

Update 3:
The issue here is with the pdf (likely the scale used to evaluate the pdf), when setting those PDF to one:
```
(VECT): Results Last   3 iters: Integral =   0.7582E-02
(LTS): Results Last   3 iters: Integral =   0.7685E-02
``` 
PDF evaluate at fixed scale (100)
```
(VECT):  Results Last   3 iters: Integral =   0.1599E+02
(LTS):  Results Last   3 iters: Integral =   0.1616E+02
```

## Update 4:
Isssue witheCKM scale is fixed but MLM merging is off...

**Comment by oliviermattelaer** [comment]
issue fixed in https://bazaar.launchpad.net/~madteam/mg5amcnlo/series2.0/revision/304
